AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Service role for glue etl iam role and other necessary resources.
  It run glue job, read kinesis data stream and transform the data, and save to s3 in data lake account
  stackName=bots-taijitu-application-account-resources
Parameters:
  ENV:
    Type: String
    Default: "test"
    AllowedValues:
      - "test"
      - "prod"
    Description: "The environment to deploy the stack to"
Mappings:
  AccountMap:
    # China Prod
    "prod":
      DataAccountS3Arn: "arn:aws-cn:s3:::bots-taijitu-prod-439413396736-flatted-data"
    # China Test
    "test":
      DataAccountS3Arn: "arn:aws-cn:s3:::bots-taijitu-test-439314357471-flatted-data"
  ResourceTagMap:
    NikeStandardTags:
      "application": "bots-taijitu-data-etl"
      "department": "Web Eng - nike.com Cloud Capability"
      "domain": "DTC - CiC Bots"
      "owner": "frank.zhao@nike.com"
      "distributionlist": "Lst-gc-cdn-antibots.admin@nike.com"
      "environment": "prod"
      "tagguid": "648007d7-d23e-4bcc-8a5f-a40119600eda"
Resources:
  GlueInteractiveIAMRole:
    # DependsOn: GlueRuntimeServiceIAMRole
    Type: AWS::IAM::Role
    Properties:
      RoleName: bots-taijitu-glue-etl-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AwsGlueSessionUserRestrictedNotebookPolicy'
      Path: '/'
      Policies:
        - PolicyName: bots-taijitu-kds-read-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadStream
                Effect: Allow
                Action:
                  - kinesis:DescribeStreamSummary
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                  - kinesis:DescribeStream
                Resource:
                  - !Sub 'arn:${AWS::Partition}:kinesis:${AWS::Region}:${AWS::AccountId}:stream/launch-entry-eda-data-stream'
                  - !Sub 'arn:${AWS::Partition}:kinesis:${AWS::Region}:${AWS::AccountId}:stream/launch-entry-eda-data-stream/*'
              - Sid: ListStream
                Effect: Allow
                Action:
                  - kinesis:ListStreams
                  - kinesis:ListShards
                Resource:
                  - '*'
        - PolicyName: bots-taijitu-data-account-s3-write-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: WriteToS3
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !FindInMap [AccountMap, !Ref ENV, DataAccountS3Arn]
        - PolicyName: bots-taijitu-glue-session-notebook-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AccessGlueNotebook
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*'
                Condition:
                  StringLike:
                    'iam:PassedToService':
                      - glue.amazonaws.com
      Tags:
        - Key: "nike-tagguid"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, tagguid]
        - Key: "nike-application"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, application]
        - Key: "nike-department"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, department]
        - Key: "nike-owner"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, owner]
        - Key: "nike-distributionlist"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, distributionlist]
        - Key: "nike-environment"
          Value: !FindInMap [ResourceTagMap, NikeStandardTags, environment]
Outputs:
  GlueInteractiveIAMRoleArn:
    Description: "The ARN of the Glue etl job IAM Role"
    Value: !GetAtt GlueInteractiveIAMRole.Arn
  GlueInteractiveIAMRoleName:
    Description: "The name of the Glue etl job IAM Role"
    Value: !Ref GlueInteractiveIAMRole