AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Service role for glue data center account for bots-taijitu
  stackName=bots-taijitu-data-account-resources
Mappings:
  AccountMap:
    # China Prod
    "734147128161":
      OscarApiArn: "arn:aws-cn:execute-api:*:180957259698:*"
      OktaAdminRole: "arn:aws-cn:iam::734147128161:role/NIKE.SSO.AdminRole"
    # China Test
    "734176943427":
      OscarApiArn: "arn:aws-cn:execute-api:*:693031048477:*"
      OktaAdminRole: "arn:aws-cn:iam::734176943427:role/NIKE.SSO.AdminRole"
Resources:
  
  TaijituGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: bots_taijitu_db
        Description: glue database for storing launch related bots taijitu tables from various sources